on:
  push:
    tags:
    - '*'
  workflow_dispatch:

name: ftpu-toolchain

permissions: write-all

jobs:
  job0:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build project
        working-directory: ../
        run: |
          sudo ln -snf /bin/bash /bin/sh
          sudo mount --bind /${PWD} /opt/
          mkdir ftpu-build
          make USETAR=1 -C ftpu-build/ -f ../ftpu/makefile all > ftpu/build.log
          mv ftpu-build/ftpu-toolchain.tar.xz ftpu/ftpu-toolchain-linux-x64.tar.xz
      - name: Save build.log
        uses: actions/upload-artifact@v4
        with:
          path: build.log
          name: build.log
          if-no-files-found: error
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ftpu-toolchain-linux-x64.tar.xz
